version: "3.9"

services:
  backend:
    build:
      context: ./backend
    image: rag-chatbot-backend:latest
    env_file:
      - backend/.env.example
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - PHOENIX_ENDPOINT=http://phoenix:6006
      - PRODUCT_DATA_PATH=/data/products.jsonl
      - API_VERSION=${BACKEND_VERSION:-0.1.0}
    depends_on:
      - weaviate
      - phoenix
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data:ro
    labels:
      - org.opencontainers.image.title=rag-chatbot-backend
      - org.opencontainers.image.version=${BACKEND_VERSION:-0.1.0}

  frontend:
    build:
      context: ./frontend
    image: rag-chatbot-frontend:latest
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    labels:
      - org.opencontainers.image.title=rag-chatbot-frontend
      - org.opencontainers.image.version=${FRONTEND_VERSION:-0.1.0}

  weaviate:
    image: semitechnologies/weaviate:1.25.6
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      ENABLE_MODULES: text2vec-openai,generative-openai
      OPENAI_APIKEY: ${OPENAI_API_KEY:-changeme}
      QUERY_DEFAULTS_LIMIT: 25
      CLUSTER_HOSTNAME: weaviate

  phoenix:
    image: arizephoenix/phoenix:latest
    restart: unless-stopped
    ports:
      - "6006:6006"
    environment:
      PHOENIX_PORT: 6006
      PHOENIX_HOST: 0.0.0.0

  eval:
    build:
      context: ./evaluation
      dockerfile: Dockerfile
    image: rag-chatbot-evaluation:latest
    depends_on:
      - backend
    profiles: ["dev"]
    environment:
      - EVAL_BACKEND_URL=http://backend:8000
      - QA_DATA_PATH=/data/qa.jsonl
    volumes:
      - ./data:/data:ro
    labels:
      - org.opencontainers.image.title=rag-chatbot-evaluation
      - org.opencontainers.image.version=${BACKEND_VERSION:-0.1.0}

networks:
  default:
    name: rag-chatbot-network
